### ISSUE TITLE
Avoid recent python syntax sugar to make it work for older versions of python 3

### ISSUE THREAD

**Issue by msramalho** [bellingcat/geoclustering#14]
Case in point with `:=`: https://github.com/bellingcat/geoclustering/blob/6a5cb3c3c34c6b483c9fe662685822e4c233a032/geoclustering/io.py#L67

This could easily be added to the CI pipeline by adding an older version here: https://github.com/bellingcat/geoclustering/blob/ff094a1d3e58f7df0b3de5ed5e0cf22c07cca46e/.github/workflows/main.yml#L31-L48

**Comment by fspoettel** [comment]
I fixed this and updated CI to run tests in 3.7 as well - if we want a more comprehensible check, we need to use something like flake8. I skipped adding that for now.
