### ISSUE TITLE
Add new output format: csv with cluster info

### ISSUE THREAD

**Issue by msramalho** [bellingcat/geoclustering#15]
Idea is just to output the data as a csv, but with a new column `cluster` so it's easier to analyse/filter results, should complement the txt output.

**Comment by fspoettel** [comment]
Do we still need the text output if this is implemented?

**Comment by msramalho** [comment]
I'd leave it since text is still easier to read for some people than csv

**Comment by kashyapm94** [comment]
@msramalho is someone working on this issue? If not, I would like to work on it
